kind: pipeline
name: default

clone:
  disable: true
  

steps:
  
    
- name: checkversion
  image: registry.bioclinr.com:10021/jenkinspipeline/rstudio_devel:v1
  entrypoint: [bash]
  commands:
  - echo "Hello world"
