kind: pipeline
name: default

steps:
- name: teststep
  image: ubuntu
  commands:
  - echo "Hello world!2"
  - pwd
  - ls
  
- name: gittest
  image: plugins/git
  commands:
  - git branch -a
  - sleep 100
