# Drone starts with an empty directory
#todo: put git clone into plugin

kind: pipeline
name: default

clone:
  disable: true
  
steps:
- name: build
  image: alpine
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
    TESTVALUE:
      from_secret: test_value
  commands:
  - echo "Hello ${TEST_VALUE}"
