# Drone starts with an empty repository

kind: pipeline
name: default

clone:
  disable: true
  
steps:
- name: gittest
# we don't take drone/git because it only has five parameters and we need a more customized git setup
  image: plugins/git
  commands:
  - git clone "$DRONE_GIT_HTTP_URL"
  - git checkout --track origin/master # checkout master with attached head (--track) to compare R versions
  - git status
  - git checkout "$DRONE_COMMIT
  - git status
  - git branch -a

- name: teststep
  image: ubuntu
  commands:
  - echo "Hello world!2"
  - pwd
  - ls
  
