#!/usr/bin/env Rscript

# This file was generated by Jenkins pipeline
# used to install packages mainly
# todo: fail if not found: how?? as install.packages fails silently without error
# not working: withCallingHandlers(install.packages("helloRpkg_21.0.0.tar.gz", repos = NULL, type="source"), warning = function(w) stop(w))
install.packages("helloRpkg_21.0.0.tar.gz", repos = NULL, type="source")
